// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBjvnqTdVHDjOwIWuSk1by67NelzWydbA',
    appId: '1:662220757823:web:70f5feafe5d17038fe918a',
    messagingSenderId: '662220757823',
    projectId: 'flutter-chat-app-fdb76',
    authDomain: 'flutter-chat-app-fdb76.firebaseapp.com',
    storageBucket: 'flutter-chat-app-fdb76.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxTpsG6fT1n2ewJKXreXylo6pq-sH5KAs',
    appId: '1:662220757823:android:94fdce858d68643ffe918a',
    messagingSenderId: '662220757823',
    projectId: 'flutter-chat-app-fdb76',
    storageBucket: 'flutter-chat-app-fdb76.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABhUgTMYtK-j_2SjmO8GvXvQzVzJeXdbA',
    appId: '1:662220757823:ios:271d31cb2e4d3cc0fe918a',
    messagingSenderId: '662220757823',
    projectId: 'flutter-chat-app-fdb76',
    storageBucket: 'flutter-chat-app-fdb76.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABhUgTMYtK-j_2SjmO8GvXvQzVzJeXdbA',
    appId: '1:662220757823:ios:271d31cb2e4d3cc0fe918a',
    messagingSenderId: '662220757823',
    projectId: 'flutter-chat-app-fdb76',
    storageBucket: 'flutter-chat-app-fdb76.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBjvnqTdVHDjOwIWuSk1by67NelzWydbA',
    appId: '1:662220757823:web:f9244a7220c524a4fe918a',
    messagingSenderId: '662220757823',
    projectId: 'flutter-chat-app-fdb76',
    authDomain: 'flutter-chat-app-fdb76.firebaseapp.com',
    storageBucket: 'flutter-chat-app-fdb76.appspot.com',
  );
}